(define (MOVE N FROM TO SPARE)
  (cond ((= N 0))
	(else
	  (MOVE (- N 1) FROM SPARE TO)
	  (display "MOV ")
	  (display N)
	  (display " FROM ")
	  (display FROM)
	  (display " TO ")
	  (display TO)
	  (newline)
	  (MOVE (- N 1) SPARE TO FROM))))
(MOVE 4 "start" "target" "tmp")
