(define (sqrt x)
  (define tolerance 0.0000001)
  (define (abs y)
    (if (< y 0)
      (- y)
      y))
  (define (average y1 y2)
    (/ (+ y1 y2) 2))
  (define (good-enough? y)
    (< (abs (- (* y y)
	       x))
       tolerance))
  (define (improve y)
    (average (/ x y) y))
  (define (try y)
    (if (good-enough? y)
      y
      (try (improve y))))
  (try 1))
(display (sqrt 2))
