(define (cons x y)
  (* (expt 2 x) (expt 3 y)))
(define (car x)
  (if (= ((lambda (x) (cond ((= (remainder x 2) 0) 1)
							 (#t 0))) x)
		 1)
		 (+ 1 (car (/ x 2)))
		 0))
(define (cdr x)
  (if (= ((lambda (x) (cond ((= (remainder x 3) 0) 1)
							 (#t 0))) x)
		 1)
		 (+ 1 (cdr (/ x 3)))
		 0))

(define x (cons 131 115))
(display x)
(newline)
(display (car x))
(newline)
(display (cdr x))
(newline)
