(define (make-interval a b) (cons a b))
(define (upper-bound interval) (cdr interval))
(define (lower-bound interval) (car interval))

(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
				 (+ (upper-bound x) (upper-bound y))))

(define (sub-interval x y)
  (make-interval (- (lower-bound x) (upper-bound y))
				 (- (upper-bound x) (lower-bound y))))

(define (mul-interval x y)
  (let ((p1 (* (lower-bound x) (lower-bound y)))
		(p2 (* (lower-bound x) (upper-bound y)))
		(p3 (* (upper-bound x) (lower-bound y)))
		(p4 (* (upper-bound x) (upper-bound y))))
	(make-interval (min p1 p2 p3 p4)
				   (max p1 p2 p3 p4))))

(define (div-interval x y)
  (if (<= (* (upper-bound y) (lower-bound y)) 0)
	#f
	(mul-interval x
				  (make-interval (/ 1.0 (upper-bound y))
								 (/ 1.0 (lower-bound y))))))

(define (mul-interval x y)
  (let ((lx (lower-bound x))
		(ux (upper-bound x))
		(ly (lower-bound y))
		(uy (upper-bound y)))
	(let ((pos-lx? (positive? lx))
		  (pos-ux? (positive? ux))
		  (pos-ly? (positive? ly))
		  (pos-uy? (positive? uy)))
	  (cond ((and (not pos-lx?) (not pos-ly?)) (make-interval (* lx ly) (* ux uy)))
			((and (not pos-lx?) pos-ly? (not pos-uy?)) (make-interval (* ux ly) (* ux uy)))
			((and (not pos-lx?) pos-uy?) (make-interval (* ux ly) (* lx uy)))
			((and pos-lx? (not pos-ux?) (not pos-ly?)) (make-interval (* lx uy) (* ux uy)))
			((and pos-lx? (not pos-ux?) pos-ly? (not pos-uy?)) (let ((l1 (* ux ly))
																	 (l2 (* lx uy))
																	 (u1 (* ux uy))
																	 (u2 (* lx ly)))
																 (make-interval (min l1 l2) (max u1 u2))))
			((and pos-lx? (not pos-ux?) pos-uy?) (make-interval (* ux ly) (* lx ly)))
			((and pos-ux? (not pos-ly?)) (make-interval (* lx uy) (* ux ly)))
			((and pos-ux? pos-ly? (not pos-uy?)) (make-interval (* lx uy) (* lx ly)))
			((and pos-ux? pos-uy?) (make-interval (* ux uy) (* lx ly)))))))

(define (make-center-width c w)
  (make-interval (- c w) (+ c w)))

(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))

(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))

(define (make-center-percent c p)
	(make-center-width c (* c (/ p 100))))

(define (percent i)
  (* (/ (width i) (center i)) 100))

(define test (make-center-width 10 1))
(display test)
(newline)
(display (center test))
(newline)
(display (width test))
(newline)
(display (percent test))
(newline)
(display (make-center-percent (center test) (percent test)))
(newline)
