(define (* a b)
  (define (double x)
	(+ x x))
  (define (halve x)
	(/ x 2))
  (define (iter res a b)
	(cond ((= b 0) res)
		  ((even? b) (iter res (double a) (halve b)))
		  (else (iter (+ res a) a (- b 1)))))
  (iter 0 a b))
