(define (integral f a b)
  (define n 1000)
  (define h (/ (- b a) n))
  (define (buildfrom1toN-1 f a b mul)
	(cond ((> a b) 0)
		  (#t (+ (* (f a) mul)
				 (buildfrom1toN-1 f (+ a h) b (+ (remainder mul 4) 2))))))
  (/ (* (+ (f a) (buildfrom1toN-1 f (+ a h) (- b h) 4) (f b))
		h)
	 3.0))

(define (cube x)
  (* x x x))
(display (integral cube 0 1))
(newline)
