(define (cons x y)
  (lambda (m)
	(cond ((= m 0) x)
		  ((= m 1) y))))
(define (car x) (x 0))
(define (cdr x) (x 1))

(define message (cons "Hello" "World"))
(begin
  (newline)
  (display (car message))
  (newline)
  (display (cdr message))
  (newline)
  )
